export const futuristicShoesData = [
  {
    name: "Quantum Stride X",
    number: "n.001",
    price: 89.99,
    id: "FUT001",
    color: "Blue",
    availableSizes: [8, 9, 10, 11],
    description:
      "Experience next-level comfort and performance with the Quantum Stride X. Cutting-edge technology meets futuristic design for the ultimate running sensation.",
    material: "Breathable Mesh Upper, Lightweight Synthetic Sole",
    newItem: true,
  },
  {
    name: "NeuraGlide 3000",
    number: "n.002",
    price: 79.99,
    id: "FUT002",
    color: "Black",
    availableSizes: [7, 8, 9, 10, 11],
    description:
      "Step into the future of style and support with NeuraGlide 3000. Engineered for maximum comfort and sleek aesthetics, these shoes redefine your every step.",
    material: "Premium Synthetic Leather, Responsive Foam Midsole",
    newItem: false,
  },
  {
    name: "HyperFlex Nexus",
    number: "n.003",
    price: 99.99,
    id: "FUT003",
    color: "Silver",
    availableSizes: [8, 9, 10, 11, 12],
    description:
      "Achieve unparalleled flexibility and performance with HyperFlex Nexus. These shoes seamlessly blend futuristic design with advanced technology to elevate your athletic experience.",
    material: "Flexible Knit Fabric, Durable Rubber Outsole",
    newItem: false,
  },
  {
    name: "Cosmic Trek Pro",
    number: "n.004",
    price: 119.99,
    id: "FUT004",
    color: "Red",
    availableSizes: [7, 8, 9, 10],
    description:
      "Embark on a cosmic journey with Cosmic Trek Pro. Precision engineering and vibrant design make these shoes the perfect companion for your adventurous spirit.",
    material: "Water-Resistant Synthetic, Shock-Absorbing Midsole",
    newItem: false,
  },
  {
    name: "Galactic Elegance",
    number: "n.005",
    price: 109.99,
    id: "FUT005",
    color: "White",
    availableSizes: [6, 7, 8, 9, 10],
    description:
      "Indulge in elegance and comfort with Galactic Elegance. These shoes seamlessly blend futuristic aesthetics with timeless style for a sophisticated look.",
    material: "Soft Microfiber Upper, Traction-enhancing Rubber Sole",
    newItem: false,
  },
  {
    name: "Zero-G Levitate",
    number: "n.006",
    price: 59.99,
    id: "FUT006",
    color: "Green",
    availableSizes: [7, 8, 9, 10, 11],
    description:
      "Defy gravity with the Zero-G Levitate. These lightweight and responsive shoes provide a dynamic feel for an out-of-this-world walking experience.",
    material: "Ultra-Lightweight Synthetic, BounceBack Foam Midsole",
    newItem: false,
  },
  {
    name: "Quantum Stride Ultra",
    number: "n.007",
    price: 94.99,
    id: "FUT007",
    color: "Purple",
    availableSizes: [8, 9, 10],
    description:
      "Unleash your potential with the Quantum Stride Ultra. Engineered for maximum energy return and comfort, these shoes are the perfect blend of style and performance.",
    material: "Durable Mesh Upper, Energy-Return Technology",
    newItem: false,
  },
  {
    name: "AeroGlide SynthX",
    number: "n.008",
    price: 79.99,
    id: "FUT008",
    color: "Orange",
    availableSizes: [7, 8, 9, 10, 11, 12],
    description:
      "Soar through the air with the AeroGlide SynthX. These futuristic shoes combine aerodynamic design with advanced cushioning for an unparalleled gliding experience.",
    material: "Synthetic Aero-Fiber Upper, Responsive Cushioning",
    newItem: true,
  },
  {
    name: "Nebula Flux Sandals",
    number: "n.009",
    price: 49.99,
    id: "FUT009",
    color: "Yellow",
    availableSizes: [6, 7, 8, 9, 10],
    description:
      "Step into the future of casual comfort with Nebula Flux Sandals. These sandals feature a lightweight design and cushioned footbed for all-day relaxation.",
    material: "Soft EVA Straps, Contoured Footbed",
    newItem: true,
  },
  {
    name: "GravityShift Trailblazer",
    number: "n.010",
    price: 109.99,
    id: "FUT010",
    color: "Cyan",
    availableSizes: [7, 8, 9, 10, 11],
    description:
      "Conquer any trail with the GravityShift Trailblazer. These rugged yet stylish shoes provide superior grip and stability for your outdoor adventures.",
    material: "Waterproof Synthetic, Durable Traction Outsole",
    newItem: false,
  },
  {
    name: "PlasmaStep Elite",
    number: "n.011",
    price: 99.99,
    id: "FUT011",
    color: "Magenta",
    availableSizes: [8, 9, 10],
    description:
      "Elevate your performance with the PlasmaStep Elite. These high-tech shoes offer precision fit and responsive cushioning for your most intense workouts.",
    material: "Ventilated Mesh Upper, High-Rebound Foam Midsole",
    newItem: false,
  },
  {
    name: "TechStride Infinity",
    number: "n.012",
    price: 84.99,
    id: "FUT012",
    color: "Gray",
    availableSizes: [7, 8, 9, 10, 11, 12],
    description:
      "Step into the future of style and comfort with TechStride Infinity. These versatile shoes feature a sleek design and advanced cushioning for everyday wear.",
    material: "Durable Textile Upper, Memory Foam Insole",
    newItem: false,
  },
  {
    name: "QuantumFlow EvoX",
    number: "n.013",
    price: 74.99,
    id: "FUT013",
    color: "Pink",
    availableSizes: [6, 7, 8, 9],
    description:
      "Experience the fluidity of motion with QuantumFlow EvoX. These shoes are designed for agility and style, making them the perfect choice for dynamic activities.",
    material: "Flexible Knit Upper, Responsive EVA Midsole",
    newItem: false,
  },
  {
    name: "MegaGrip Fusion",
    number: "n.014",
    price: 114.99,
    id: "FUT014",
    color: "Turquoise",
    availableSizes: [8, 9, 10, 11],
    description:
      "Conquer any terrain with MegaGrip Fusion. These shoes feature a high-traction outsole and durable construction for superior performance on your outdoor adventures.",
    material: "Waterproof Synthetic, MegaGrip Rubber Outsole",
    newItem: false,
  },
  {
    name: "NexaFlex Precision",
    number: "n.015",
    price: 69.99,
    id: "FUT015",
    color: "Lime",
    availableSizes: [7, 8, 9, 10],
    description:
      "Unleash your precision with NexaFlex Precision. These shoes offer a responsive feel and precise fit, making them the ideal choice for focused workouts.",
    material: "Breathable Mesh Upper, PrecisionFit Lacing System",
    newItem: false,
  },
  {
    name: "XenonTech Velocity",
    number: "n.016",
    price: 97.99,
    id: "FUT016",
    color: "Brown",
    availableSizes: [8, 9, 10, 11, 12],
    description:
      "Experience the speed of technology with XenonTech Velocity. These shoes feature advanced materials and design for a fast and responsive feel during your runs.",
    material: "Lightweight Synthetic Upper, SpeedFoam Technology",
    newItem: false,
  },
  {
    name: "QuantumBounce React",
    number: "n.017",
    price: 88.99,
    id: "FUT017",
    color: "Olive",
    availableSizes: [7, 8, 9],
    description:
      "Bounce into the future with QuantumBounce React. These shoes feature responsive cushioning and a dynamic design for a lively and comfortable walking experience.",
    material: "EnergyBounce Foam, Durable Mesh Upper",
    newItem: false,
  },
  {
    name: "IonSync Boost",
    number: "n.018",
    price: 104.99,
    id: "FUT018",
    color: "Teal",
    availableSizes: [8, 9, 10, 11],
    description:
      "Sync up with IonSync Boost for a boost in performance. These shoes feature responsive cushioning and a supportive fit for your most demanding activities.",
    material: "Synthetic Upper, Boost Cushioning",
    newItem: false,
  },
  {
    name: "SkyWeave Nimbus",
    number: "n.019",
    price: 92.99,
    id: "FUT019",
    color: "Gold",
    availableSizes: [7, 8, 9, 10],
    description:
      "Walk on clouds with SkyWeave Nimbus. These lightweight and breathable shoes offer a luxurious feel for your daily adventures.",
    material: "Premium Woven Fabric Upper, CloudComfort Insole",
    newItem: true,
  },
  {
    name: "EcoDrive SynthWave",
    number: "n.020",
    price: 54.99,
    id: "FUT020",
    color: "Silver",
    availableSizes: [6, 7, 8, 9],
    description:
      "Experience sustainable style with EcoDrive SynthWave. These eco-friendly shoes feature recycled materials and a sleek design for a guilt-free fashion statement.",
    material: "Recycled Synthetic Leather, EcoFoam Midsole",
    newItem: false,
  },
  {
    name: "VortexTech HyperStep",
    number: "n.021",
    price: 79.99,
    id: "FUT021",
    color: "Indigo",
    availableSizes: [8, 9, 10, 11, 12],
    description:
      "Step into the vortex of technology with VortexTech HyperStep. These shoes feature advanced materials and a futuristic design for a cutting-edge look and feel.",
    material: "HyperTech Mesh Upper, VortexFoam Cushioning",
    newItem: true,
  },
  {
    name: "LunarGlide UltraX",
    number: "n.022",
    price: 109.99,
    id: "FUT022",
    color: "Bronze",
    availableSizes: [7, 8, 9, 10],
    description:
      "Glide through the lunar landscape with LunarGlide UltraX. These shoes offer a smooth and stable ride for your runs and workouts.",
    material: "LunarWeave Upper, UltraGlide Midsole",
    newItem: true,
  },
  {
    name: "QuantumShift Flux",
    number: "n.023",
    price: 96.99,
    id: "FUT023",
    color: "Crimson",
    availableSizes: [8, 9, 10, 11],
    description:
      "Shift into high gear with QuantumShift Flux. These high-performance shoes feature a dynamic design and responsive cushioning for your fastest moves.",
    material: "FlexTech Upper, FluxFoam Technology",
    newItem: true,
  },
  {
    name: "NanoFlex Stratos",
    number: "n.024",
    price: 68.99,
    id: "FUT024",
    color: "Azure",
    availableSizes: [7, 8, 9],
    description:
      "Flex into the future with NanoFlex Stratos. These shoes offer exceptional flexibility and lightweight comfort for your everyday activities.",
    material: "NanoFlex Fabric Upper, FlexFoam Insole",
    newItem: false,
  },
  {
    name: "XenonForce Propel",
    number: "n.025",
    price: 119.99,
    id: "FUT025",
    color: "Ruby",
    availableSizes: [8, 9, 10, 11],
    description:
      "Propel yourself forward with XenonForce Propel. These shoes feature a propulsive design and responsive cushioning for explosive performance.",
    material: "XenonMesh Upper, PropelFoam Midsole",
    newItem: false,
  },
  {
    name: "GravityWave Pulse",
    number: "n.026",
    price: 84.99,
    id: "FUT026",
    color: "Platinum",
    availableSizes: [7, 8, 9, 10],
    description:
      "Feel the pulse of gravity with GravityWave Pulse. These shoes provide a stable and cushioned ride for your daily activities.",
    material: "StabilTech Upper, PulseFoam Cushioning",
    newItem: true,
  },
  {
    name: "TechGlide InfinityX",
    number: "n.027",
    price: 74.99,
    id: "FUT027",
    color: "Emerald",
    availableSizes: [8, 9, 10, 11, 12],
    description:
      "Glide into infinity with TechGlide InfinityX. These shoes feature a seamless design and advanced cushioning for a smooth and comfortable walking experience.",
    material: "TechWeave Upper, InfinityFoam Midsole",
    newItem: true,
  },
  {
    name: "QuantumBlast Xcel",
    number: "n.028",
    price: 112.99,
    id: "FUT028",
    color: "Sapphire",
    availableSizes: [7, 8, 9],
    description:
      "Blast into excellence with QuantumBlast Xcel. These high-performance shoes feature explosive design and responsive cushioning for your most dynamic movements.",
    material: "BlastTech Upper, XcelFoam Technology",
    newItem: false,
  },
  {
    name: "SkyVibe Velocity",
    number: "n.029",
    price: 99.99,
    id: "FUT029",
    color: "Rose",
    availableSizes: [8, 9, 10, 11],
    description:
      "Feel the velocity of the sky with SkyVibe Velocity. These shoes feature a lightweight design and responsive cushioning for an uplifting walking experience.",
    material: "SkyTech Mesh Upper, VelocityFoam Midsole",
    newItem: true,
  },
  {
    name: "ElectraFit Zephyr",
    number: "n.030",
    price: 64.99,
    id: "FUT030",
    color: "Amber",
    availableSizes: [7, 8, 9],
    description:
      "Embrace the electrifying comfort of ElectraFit Zephyr. These shoes feature a futuristic design and responsive cushioning for your active lifestyle.",
    material: "ElectraMesh Upper, ZephyrFoam Midsole",
    newItem: false,
  },
];
